


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."ai_images" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "kind" "text" NOT NULL,
    "scene" "text",
    "storage_path" "text" NOT NULL,
    "prompt" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "group_id" "uuid" DEFAULT "gen_random_uuid"(),
    CONSTRAINT "ai_images_kind_check" CHECK (("kind" = ANY (ARRAY['original'::"text", 'generated'::"text"])))
);


ALTER TABLE "public"."ai_images" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."camera_emotion_log" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "emotion" "text" NOT NULL,
    "confidence" numeric DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."camera_emotion_log" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."conversation_log" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "profile_id" "uuid",
    "role" "text" NOT NULL,
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "metadata" "jsonb"
);


ALTER TABLE "public"."conversation_log" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."mirror_chat_log" (
    "id" bigint NOT NULL,
    "user_id" "uuid" NOT NULL,
    "role" "text" NOT NULL,
    "message" "text",
    "metadata" "jsonb",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    CONSTRAINT "mirror_chat_log_role_check" CHECK (("role" = ANY (ARRAY['user'::"text", 'assistant'::"text"])))
);


ALTER TABLE "public"."mirror_chat_log" OWNER TO "postgres";


ALTER TABLE "public"."mirror_chat_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."mirror_chat_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."mood_entry" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "profile_id" "uuid",
    "mood" "text" NOT NULL,
    "note" "text",
    "source" "text" DEFAULT 'manual'::"text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."mood_entry" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."personality_quiz" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nickname" "text",
    "mbti_result" "text",
    "enneagram_result" "text",
    "focus_note" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."personality_quiz" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profile" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "nickname" "text" NOT NULL,
    "focus_areas" "text"[] DEFAULT '{}'::"text"[],
    "consent_camera" boolean DEFAULT false,
    "consent_data" boolean DEFAULT false,
    "mood_baseline" "text" DEFAULT 'tenang'::"text",
    "mbti_type" "text",
    "enneagram_type" "text",
    "primary_archetype" "text",
    "zodiac_sign" "text",
    "personality_notes" "text",
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()),
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."profile" OWNER TO "postgres";


ALTER TABLE ONLY "public"."ai_images"
    ADD CONSTRAINT "ai_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."camera_emotion_log"
    ADD CONSTRAINT "camera_emotion_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."conversation_log"
    ADD CONSTRAINT "conversation_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."mirror_chat_log"
    ADD CONSTRAINT "mirror_chat_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."mood_entry"
    ADD CONSTRAINT "mood_entry_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."personality_quiz"
    ADD CONSTRAINT "personality_quiz_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profile"
    ADD CONSTRAINT "profile_pkey" PRIMARY KEY ("id");



CREATE INDEX "ai_images_group_id_idx" ON "public"."ai_images" USING "btree" ("group_id");



ALTER TABLE ONLY "public"."ai_images"
    ADD CONSTRAINT "ai_images_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."conversation_log"
    ADD CONSTRAINT "conversation_log_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profile"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."mirror_chat_log"
    ADD CONSTRAINT "mirror_chat_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."mood_entry"
    ADD CONSTRAINT "mood_entry_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profile"("id") ON DELETE CASCADE;



CREATE POLICY "Users can insert own chats" ON "public"."mirror_chat_log" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can see own chats" ON "public"."mirror_chat_log" FOR SELECT USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."ai_images" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ai_images delete own" ON "public"."ai_images" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "ai_images insert own" ON "public"."ai_images" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "ai_images select own" ON "public"."ai_images" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."camera_emotion_log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."conversation_log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."mirror_chat_log" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."mood_entry" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "mood_public_rw" ON "public"."mood_entry" USING (true) WITH CHECK (true);



ALTER TABLE "public"."personality_quiz" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profile" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "profile_public_rw" ON "public"."profile" USING (true) WITH CHECK (true);



CREATE POLICY "sandbox camera access" ON "public"."camera_emotion_log" USING (true) WITH CHECK (true);



CREATE POLICY "sandbox conversation access" ON "public"."conversation_log" USING (true) WITH CHECK (true);



CREATE POLICY "sandbox mood access" ON "public"."mood_entry" USING (true) WITH CHECK (true);



CREATE POLICY "sandbox profile access" ON "public"."profile" USING (true) WITH CHECK (true);



CREATE POLICY "sandbox quiz access" ON "public"."personality_quiz" USING (true) WITH CHECK (true);



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."ai_images" TO "anon";
GRANT ALL ON TABLE "public"."ai_images" TO "authenticated";
GRANT ALL ON TABLE "public"."ai_images" TO "service_role";



GRANT ALL ON TABLE "public"."camera_emotion_log" TO "anon";
GRANT ALL ON TABLE "public"."camera_emotion_log" TO "authenticated";
GRANT ALL ON TABLE "public"."camera_emotion_log" TO "service_role";



GRANT ALL ON TABLE "public"."conversation_log" TO "anon";
GRANT ALL ON TABLE "public"."conversation_log" TO "authenticated";
GRANT ALL ON TABLE "public"."conversation_log" TO "service_role";



GRANT ALL ON TABLE "public"."mirror_chat_log" TO "anon";
GRANT ALL ON TABLE "public"."mirror_chat_log" TO "authenticated";
GRANT ALL ON TABLE "public"."mirror_chat_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."mirror_chat_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."mirror_chat_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."mirror_chat_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."mood_entry" TO "anon";
GRANT ALL ON TABLE "public"."mood_entry" TO "authenticated";
GRANT ALL ON TABLE "public"."mood_entry" TO "service_role";



GRANT ALL ON TABLE "public"."personality_quiz" TO "anon";
GRANT ALL ON TABLE "public"."personality_quiz" TO "authenticated";
GRANT ALL ON TABLE "public"."personality_quiz" TO "service_role";



GRANT ALL ON TABLE "public"."profile" TO "anon";
GRANT ALL ON TABLE "public"."profile" TO "authenticated";
GRANT ALL ON TABLE "public"."profile" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







